import test from 'node:test';
import assert from 'node:assert/strict';
import { chromium } from '@playwright/test';
import { mkdtempSync, mkdirSync, writeFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { createApp } from '../server.js';

test('실제 Chromium WebAuthn 인증과 HTTP 접근 제어', { timeout: 120000 }, async () => {
  const dir = mkdtempSync(join(tmpdir(), 'passkey-test-'));
  const origin = 'http://localhost:3108';
  let time = Date.now();
  const { app, db } = createApp({ origin, rpID: 'localhost', dbPath: join(dir, 'test.sqlite'), now: () => time });
  const server = app.listen(3108);
  await new Promise(r => server.once('listening', r));
  const browser = await chromium.launch({ channel: process.env.TEST_BROWSER || 'chrome', headless: true });
  const context = await browser.newContext({ viewport: { width: 1280, height: 900 } });
  const page = await context.newPage();
  const cdp = await context.newCDPSession(page);
  const records = [];
  const evidenceDir = resolve('docs/task8/evidence');
  mkdirSync(evidenceDir, { recursive: true });
  const record = (name, status, expected) => { assert.equal(status, expected, name); records.push({ test: name, status, result: 'PASS' }); };
  const req = (path, data, method = 'POST') => context.request.fetch(`${origin}/api${path}`, { method, headers: { Origin: origin, 'Content-Type': 'application/json' }, ...(method === 'GET' ? {} : { data: data || {} }) });
  async function flow(path, data) { const r = await req(path, data); assert.equal(r.status(), 200, await r.text()); return r.json(); }
  async function authenticator() { return (await cdp.send('WebAuthn.addVirtualAuthenticator', { options: { protocol: 'ctap2', transport: 'usb', hasResidentKey: true, hasUserVerification: true, isUserVerified: true, automaticPresenceSimulation: true } })).authenticatorId; }
  async function registration(accountName, name) {
    const f = await flow('/passkey/register/options', { accountName, name });
    const credential = await page.evaluate(optionsJSON => SimpleWebAuthnBrowser.startRegistration({ optionsJSON }), f.options);
    assert.equal(JSON.stringify(credential).includes('privateKey'), false);
    const r = await req('/passkey/register/verify', { challengeId: f.challengeId, credential });
    record(`등록 ${name}: 공개키 응답 검증`, r.status(), 200); return { credential, f };
  }
  async function assertion(accountName) {
    const f = await flow('/passkey/login/options', { accountName });
    const credential = await page.evaluate(optionsJSON => SimpleWebAuthnBrowser.startAuthentication({ optionsJSON }), f.options);
    return { challengeId: f.challengeId, credential };
  }
  try {
    await cdp.send('WebAuthn.enable');
    const auth1 = await authenticator();
    await page.goto(origin); await page.waitForFunction(() => !!window.SimpleWebAuthnBrowser);
    record('비로그인 GET /api/private', (await req('/private', null, 'GET')).status(), 401);
    record('비로그인 보관함', (await req('/vault', null, 'GET')).status(), 401);
    const html = await (await context.request.get(origin)).text();
    assert.ok(!html.includes('가상의 보안 실습')); assert.ok(!html.includes('가상 조직 Alpha'));
    records.push({ test: '비로그인 HTML에 비공개 샘플 없음', result: 'PASS' });
    await page.screenshot({ path: join(evidenceDir, '01-locked.png'), fullPage: true });
    record('다른 Origin 등록 차단', (await context.request.post(`${origin}/api/passkey/register/options`, { headers: { Origin: 'https://evil.example' }, data: {} })).status(), 403);
    const cancelled = await flow('/passkey/register/options', { accountName: 'Cancelled', name: '취소' });
    const second = await flow('/passkey/register/options', { accountName: 'Cancelled', name: '취소' });
    assert.notEqual(cancelled.options.challenge, second.options.challenge);
    records.push({ test: '서로 다른 등록 challenge', prefixes: [cancelled.options.challenge.slice(0, 8), second.options.challenge.slice(0, 8)], result: 'PASS' });
    await req('/passkey/cancel', { challengeId: cancelled.challengeId });
    assert.equal(db.prepare('SELECT count(*) n FROM credentials').get().n, 0);
    assert.equal(db.prepare('SELECT count(*) n FROM accounts').get().n, 0);
    record('취소 challenge 재검증 차단', (await req('/passkey/register/verify', { challengeId: cancelled.challengeId })).status(), 400);
    const a1 = await registration('Account-A', '내 노트북');
    const a = (await (await req('/session', null, 'GET')).json()).account.id;
    assert.ok(db.prepare('SELECT public_key FROM credentials WHERE id=?').get(a1.credential.id).public_key.length > 0);
    record('등록 challenge 재사용', (await req('/passkey/register/verify', { challengeId: a1.f.challengeId, credential: a1.credential })).status(), 400);
    record('인증 후 자기 자료', (await req('/private', null, 'GET')).status(), 200);
    const noteResponse=await req('/vault',{kind:'note',title:'테스트 비밀 제목',text:'실제 개인정보가 아닌 암호화 검증 문장'});
    record('비밀 메모 생성',noteResponse.status(),201);
    const materialId=(await noteResponse.json()).id;
    const material=(await (await req(`/vault/${materialId}`,null,'GET')).json());
    assert.equal(material.text,'실제 개인정보가 아닌 암호화 검증 문장');
    const encrypted=db.prepare('SELECT metadata,content FROM vault WHERE id=?').get(materialId);
    assert.ok(!Buffer.from(encrypted.content).includes(Buffer.from(material.text)));
    assert.ok(!Buffer.from(encrypted.metadata).includes(Buffer.from(material.title)));
    record('메모 수정',(await req(`/vault/${materialId}`,{title:'수정한 제목',text:'수정한 내용',updated:material.updated},'PUT')).status(),200);
    record('오래된 편집 충돌',(await req(`/vault/${materialId}`,{title:'덮어쓰기',text:'거절',updated:material.updated},'PUT')).status(),409);
    const fileResponse=await req('/vault',{kind:'file',title:'테스트 파일',filename:'검증.html',base64:Buffer.from('<script>alert(1)</script>').toString('base64')});
    record('파일 저장',fileResponse.status(),201);const fileId=(await fileResponse.json()).id;
    const download=await req(`/vault/${fileId}/download`,null,'GET');assert.equal(await download.text(),'<script>alert(1)</script>');assert.match(download.headers()['content-disposition'],/^attachment;/);
    record('초과 파일 거절',(await req('/vault',{kind:'file',title:'크기 검사',filename:'test.bin',base64:Buffer.alloc(5*1024*1024+1).toString('base64')})).status(),413);
    record('잘못된 파일 인코딩',(await req('/vault',{kind:'file',title:'검사',filename:'test.bin',base64:'!!!!'})).status(),400);
    const exclude = await flow('/passkey/register/options', { name: '추가' });
    assert.ok(exclude.options.excludeCredentials.some(x => x.id === a1.credential.id));
    await req('/passkey/cancel', { challengeId: exclude.challengeId });
    await cdp.send('WebAuthn.setAutomaticPresenceSimulation', { authenticatorId: auth1, enabled: false });
    const auth2 = await authenticator();
    const a2 = await registration(undefined, '내 휴대폰');
    await page.reload(); await page.waitForSelector('#authenticated:not([hidden])');
    assert.equal(await page.locator('#keys li').count(), 2);
    await page.screenshot({ path: join(evidenceDir, '02-two-passkeys.png'), fullPage: true });
    const oldCookies = await context.cookies(origin);
    const cookie = oldCookies.map(c => `${c.name}=${c.value}`).join('; ');
    await req('/logout');
    record('로그아웃 전 쿠키 재사용', (await context.request.get(`${origin}/api/private`, { headers: { Cookie: cookie } })).status(), 401);
    const l1 = await flow('/passkey/login/options', { accountName: 'Account-A' });
    const l2 = await flow('/passkey/login/options', { accountName: 'Account-A' });
    assert.notEqual(l1.options.challenge, l2.options.challenge);
    records.push({ test: '서로 다른 로그인 challenge', prefixes: [l1.options.challenge.slice(0, 8), l2.options.challenge.slice(0, 8)], result: 'PASS' });
    const bad = await assertion('Account-A');
    const sig = Buffer.from(bad.credential.response.signature, 'base64url'); sig[sig.length - 1] ^= 1;
    bad.credential.response.signature = sig.toString('base64url');
    record('잘못된 서명', (await req('/passkey/login/verify', bad)).status(), 401);
    record('실패한 challenge 재사용', (await req('/passkey/login/verify', bad)).status(), 400);
    const good = await assertion('Account-A');
    record('정상 서명 로그인', (await req('/passkey/login/verify', good)).status(), 200);
    record('정상 assertion 재사용', (await req('/passkey/login/verify', good)).status(), 400);
    await req('/logout');
    const b1 = await registration('Account-B', 'B의 기기');
    const b = (await (await req('/session', null, 'GET')).json()).account.id;
    for(const [suffix,method,body] of [['','GET',null],['/download','GET',null],['','PUT',{title:'공격',text:'실패',updated:material.updated}],['','DELETE',{}]]) {
      record(`B → A 자료 ${method} ${suffix}`,(await req(`/vault/${materialId}${suffix}`,body,method)).status(),404);
    }
    assert.equal((await (await req('/vault',null,'GET')).json()).items.length,0);
    record('B → A query', (await req(`/private?userId=${a}`, null, 'GET')).status(), 403);
    record('B → A path', (await req(`/private/${a}`, null, 'GET')).status(), 403);
    record('B → A body', (await req('/private', { accountId: a })).status(), 403);
    record('B → A 패스키 삭제', (await req(`/passkeys/${a1.credential.id}`, {}, 'DELETE')).status(), 404);
    await req('/logout');
    const another = await assertion('Account-B');
    const aFlow = await flow('/passkey/login/options', { accountName: 'Account-A' });
    record('다른 계정 credential', (await req('/passkey/login/verify', { ...another, challengeId: aFlow.challengeId })).status(), 401);
    const loginA = await assertion('Account-A'); await req('/passkey/login/verify', loginA);
    assert.equal((await (await req(`/vault/${materialId}`,null,'GET')).json()).text,'수정한 내용');
    record('메모 삭제',(await req(`/vault/${materialId}`,{},'DELETE')).status(),200);
    record('파일 삭제',(await req(`/vault/${fileId}`,{},'DELETE')).status(),200);
    record('삭제 자료 조회',(await req(`/vault/${materialId}`,null,'GET')).status(),404);
    record('A → B query', (await req(`/private?userId=${b}`, null, 'GET')).status(), 403);
    record('A → B path', (await req(`/private/${b}`, null, 'GET')).status(), 403);
    record('A → B body', (await req('/private', { userId: b })).status(), 403);
    assert.equal(db.prepare('SELECT count(*) n FROM notes WHERE account=?').get(a).n, 3);
    assert.equal(db.prepare('SELECT count(*) n FROM notes WHERE account=?').get(b).n, 3);
    records.push({ test: '교차 접근 거절 후 A/B 자료 개수', before: [3, 3], after: [3, 3], result: 'PASS' });
    const deletedCredentialOptions = await flow('/passkey/login/options', { accountName: 'Account-A' });
    record('패스키 1 삭제', (await req(`/passkeys/${a1.credential.id}`, {}, 'DELETE')).status(), 200);
    record('삭제 직후 기존 인증 차단', (await req('/private', null, 'GET')).status(), 401);
    const remaining = await assertion('Account-A');
    record('남은 패스키 로그인', (await req('/passkey/login/verify', remaining)).status(), 200);
    await req('/logout');
    const fresh = await flow('/passkey/login/options', { accountName: 'Account-A' });
    // Force a deleted credential in the virtual authenticator, but sign the NEW server challenge.
    await cdp.send('WebAuthn.setAutomaticPresenceSimulation', { authenticatorId: auth2, enabled: false });
    await cdp.send('WebAuthn.setAutomaticPresenceSimulation', { authenticatorId: auth1, enabled: true });
    const removedAssertion = await page.evaluate(optionsJSON => SimpleWebAuthnBrowser.startAuthentication({ optionsJSON }), { ...fresh.options, allowCredentials: [{ id: a1.credential.id, type: 'public-key', transports: ['usb'] }] });
    record('삭제한 패스키 + 새로운 challenge 로그인', (await req('/passkey/login/verify', { challengeId: fresh.challengeId, credential: removedAssertion })).status(), 401);
    record('삭제 전 발급한 challenge', (await req('/passkey/login/verify', { challengeId: deletedCredentialOptions.challengeId, credential: removedAssertion })).status(), 400);
    await cdp.send('WebAuthn.setAutomaticPresenceSimulation', { authenticatorId: auth1, enabled: false });
    await cdp.send('WebAuthn.setAutomaticPresenceSimulation', { authenticatorId: auth2, enabled: true });
    const lastLogin = await assertion('Account-A'); await req('/passkey/login/verify', lastLogin);
    record('마지막 패스키 삭제', (await req(`/passkeys/${a2.credential.id}`, {}, 'DELETE')).status(), 200);
    record('0개 계정 로그인', (await req('/passkey/login/options', { accountName: 'Account-A' })).status(), 401);
    record('0개 계정 무인증 재등록 금지', (await req('/passkey/register/options', { accountName: 'Account-A', name: '탈취' })).status(), 409);
    const expiry = await flow('/passkey/login/options', { accountName: 'Account-B' });
    time += 300001;
    record('5분 경과 challenge', (await req('/passkey/login/verify', { challengeId: expiry.challengeId, credential: b1.credential })).status(), 400);
    await page.reload();
    await page.locator('#login-account').fill('Account-B');
    await page.locator('#login-form button').click();
    await page.waitForSelector('#authenticated:not([hidden])');
    assert.equal(await page.locator('#notes article').count(), 3);
    await page.locator('#note-title').fill('화면에서 만든 메모');
    await page.locator('#note-text').fill('직접 작성한 가상 테스트 내용');
    await page.locator('#note-form button').first().click();
    await page.waitForFunction(()=>document.getElementById('materials').textContent.includes('화면에서 만든 메모'));
    await page.reload();await page.waitForSelector('#materials article');
    await page.getByRole('button',{name:'열기 / 수정'}).click();
    await page.waitForFunction(()=>document.getElementById('note-text').value==='직접 작성한 가상 테스트 내용');
    await page.screenshot({path:join(evidenceDir,'05-vault.png'),fullPage:true});
    records.push({test:'메모 UI 작성·저장·새로고침·다시 열기',result:'PASS'});
    await page.locator('#logout').click();
    await page.waitForSelector('#entry:not([hidden])');
    assert.equal(await page.locator('#notes article').count(), 0);
    records.push({ test: '실제 로그인·로그아웃 버튼 및 DOM 데이터 제거', result: 'PASS' });
    await page.setViewportSize({ width: 390, height: 844 }); await page.reload();
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    await page.screenshot({ path: join(evidenceDir, '03-mobile.png'), fullPage: true });
    writeFileSync(join(evidenceDir, 'http-results.json'), JSON.stringify({ environment: 'Local Chromium virtual authenticator; real WebAuthn library verification, no verification mocks', generatedAt: new Date().toISOString(), records }, null, 2));
    console.log(`${records.length} HTTP/security evidence checks passed (session/cookie/signature values omitted)`);
  } finally {
    await browser.close(); await new Promise(r => server.close(r)); db.close();
    assert.ok(resolve(dir).startsWith(resolve(tmpdir()) + (process.platform === 'win32' ? '\\' : '/')));
    rmSync(dir, { recursive: true, force: true });
  }
});
