'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const C=require('../core');
const fixtures=path.join(__dirname,'..','assets','fixtures');const get=name=>JSON.parse(fs.readFileSync(path.join(fixtures,`${name}.json`),'utf8'));
test('KST 날짜는 UTC 날짜를 그대로 쓰지 않는다',()=>assert.equal(C.kstDate('2026-08-23T16:00:00.000Z'),'2026-08-24'));
test('D1-A/D1-B/D2 atomic upsert와 delta',()=>{let s=C.emptyState();s=C.runFixture(s,get('normal-d1-a'));const id=s.daily_readings[0].record_id;s=C.runFixture(s,get('normal-d1-b'));assert.equal(s.daily_readings.length,1);assert.equal(s.daily_readings[0].record_id,id);assert.equal(s.current_reading.normalized_value,105);s=C.runFixture(s,get('normal-d1-b'));assert.equal(s.daily_readings.length,1);s=C.runFixture(s,get('normal-d2'));assert.equal(s.daily_readings.length,2);assert.equal(s.comparison.signed_delta,15)});
test('변화량은 소수점 이하 최대 두 자리로 반올림한다',()=>{assert.equal(C.roundTo(25-30.2),-5.2);assert.equal(C.roundTo(1.235),1.24);assert.equal(C.roundTo(-0.001),0)});
for(const [name,code] of [['timeout','timeout'],['auth-401','auth'],['rate-429','rate_limit'],['offline','offline'],['schema-break','schema_error']])test(`${code}는 105와 1행을 보존하며 stale`,()=>{let s=C.emptyState();s=C.runFixture(s,get('normal-d1-a'));s=C.runFixture(s,get('normal-d1-b'));s=C.runFixture(s,get(name));assert.equal(s.current_reading.normalized_value,105);assert.equal(s.daily_readings.length,1);assert.deepEqual(s.status,{freshness:'stale',error_code:code})});
test('timeout 뒤 recover는 fresh/none, 2행, 120, +15',()=>{let s=C.emptyState();for(const n of ['normal-d1-a','normal-d1-b','timeout'])s=C.runFixture(s,get(n));s=C.runFixture(s,get('recover-d2'));assert.deepEqual(s.status,{freshness:'fresh',error_code:'none'});assert.equal(s.daily_readings.length,2);assert.equal(s.current_reading.normalized_value,120);assert.equal(s.comparison.signed_delta,15)});
test('실제 이틀 기록은 영수증·저장 seed에서 네 필드가 일치한다',()=>{const root=path.join(__dirname,'..');const seeds=JSON.parse(fs.readFileSync(path.join(root,'live-seed.json'),'utf8')).readings;const receipts=JSON.parse(fs.readFileSync(path.join(root,'제출정보.json'),'utf8')).과정영수증;assert.equal(seeds.length,2);assert.equal(receipts.length,2);assert.notEqual(seeds[0].record_date,seeds[1].record_date);for(let i=0;i<2;i++){assert.equal(receipts[i].kind,'t04_day');assert.equal(C.kstDate(receipts[i].server_created_at),seeds[i].record_date);assert.deepEqual(receipts[i].payload,{source_url:seeds[i].source_url,source_observed_at:seeds[i].source_time,normalized_value:seeds[i].normalized_value,unit:seeds[i].unit})}let state=C.emptyState();for(const reading of seeds)state=C.applySuccess(state,reading);assert.equal(state.comparison.signed_delta,-5)});
