const path = require('path');
const express = require('express');
const pool = require('./db');
const app = express();
const PUBLIC = path.join(__dirname, '..', 'public');
app.use(express.json({limit:'1mb'}));
app.use(express.static(PUBLIC));

const asyncRoute = fn => (req,res,next) => Promise.resolve(fn(req,res,next)).catch(next);
const allowed = (value, list, fallback) => list.includes(value) ? value : fallback;
const planFields = b => [b.title?.trim(), b.description || '', b.start_date, b.end_date, allowed(b.priority,['low','medium','high'],'medium'), b.success_criteria?.trim(), Number(b.estimated_minutes)||0, b.carried_improvement || null];
const taskFields = b => [Number(b.plan_id), b.title?.trim(), b.description || '', b.due_date, allowed(b.priority,['low','medium','high'],'medium'), b.tag || null, Number(b.estimated_minutes)||0, allowed(b.status,['todo','in_progress','completed'],'todo')];
const required = (values, names) => names.forEach((n,i)=>{if(values[i]===undefined||values[i]===null||values[i]==='') {const e=new Error(`${n} 항목은 필수입니다.`);e.status=400;throw e;}});

app.get('/api/health', asyncRoute(async(req,res)=>{await pool.query('SELECT 1');res.json({ok:true,database:'MariaDB',timezone:'Asia/Seoul'});}));
app.get('/api/plans', asyncRoute(async(req,res)=>{const [r]=await pool.execute('SELECT * FROM plans ORDER BY id DESC');res.json(r);}));
app.post('/api/plans', asyncRoute(async(req,res)=>{const v=planFields(req.body);required(v,['title','description','start_date','end_date','priority','success_criteria']);const [r]=await pool.execute('INSERT INTO plans(title,description,start_date,end_date,priority,success_criteria,estimated_minutes,carried_improvement) VALUES(?,?,?,?,?,?,?,?)',v);const [[row]]=await pool.execute('SELECT * FROM plans WHERE id=?',[r.insertId]);res.status(201).json(row);}));
app.get('/api/plans/:id', asyncRoute(async(req,res)=>{const [[row]]=await pool.execute('SELECT * FROM plans WHERE id=?',[req.params.id]);if(!row)return res.status(404).json({error:'Plan을 찾을 수 없습니다.'});res.json(row);}));
app.put('/api/plans/:id', asyncRoute(async(req,res)=>{const c=await pool.getConnection();try{await c.beginTransaction();const [[old]]=await c.execute('SELECT * FROM plans WHERE id=? FOR UPDATE',[req.params.id]);if(!old){await c.rollback();return res.status(404).json({error:'Plan을 찾을 수 없습니다.'});}await c.execute('INSERT INTO plan_history(plan_id,title,description,start_date,end_date,priority,success_criteria,estimated_minutes,carried_improvement) VALUES(?,?,?,?,?,?,?,?,?)',[old.id,old.title,old.description,old.start_date,old.end_date,old.priority,old.success_criteria,old.estimated_minutes,old.carried_improvement]);const v=planFields(req.body);required(v,['title','description','start_date','end_date','priority','success_criteria']);await c.execute('UPDATE plans SET title=?,description=?,start_date=?,end_date=?,priority=?,success_criteria=?,estimated_minutes=?,carried_improvement=? WHERE id=?',[...v,req.params.id]);await c.commit();const [[row]]=await pool.execute('SELECT * FROM plans WHERE id=?',[req.params.id]);res.json(row);}catch(e){await c.rollback();throw e;}finally{c.release();}}));
app.get('/api/plans/:id/history',asyncRoute(async(req,res)=>{const [r]=await pool.execute('SELECT * FROM plan_history WHERE plan_id=? ORDER BY history_id DESC',[req.params.id]);res.json(r);}));

app.get('/api/plans/:id/tasks',asyncRoute(async(req,res)=>{let sql=`SELECT * FROM tasks WHERE plan_id=? AND deleted_at IS NULL`;const p=[req.params.id];if(req.query.q){sql+=' AND (title LIKE ? OR description LIKE ? OR tag LIKE ?)';const q=`%${req.query.q}%`;p.push(q,q,q);}for(const f of ['status','priority','tag'])if(req.query[f]){sql+=` AND ${f}=?`;p.push(req.query[f]);}if(req.query.due==='overdue')sql+=" AND status<>'completed' AND due_date<CURRENT_DATE()";if(req.query.due==='today')sql+=' AND due_date=CURRENT_DATE()';sql+=` ORDER BY CASE WHEN status='completed' THEN 1 ELSE 0 END, CASE priority WHEN 'high' THEN 1 WHEN 'medium' THEN 2 ELSE 3 END, due_date, id`;const [r]=await pool.execute(sql,p);res.json(r);}));
app.post('/api/tasks',asyncRoute(async(req,res)=>{const v=taskFields(req.body);required(v,['plan_id','title','description','due_date','priority']);const [r]=await pool.execute('INSERT INTO tasks(plan_id,title,description,due_date,priority,tag,estimated_minutes,status) VALUES(?,?,?,?,?,?,?,?)',v);const [[row]]=await pool.execute('SELECT * FROM tasks WHERE id=?',[r.insertId]);res.status(201).json(row);}));
app.put('/api/tasks/:id',asyncRoute(async(req,res)=>{const v=taskFields(req.body);required(v,['plan_id','title','description','due_date','priority']);await pool.execute('UPDATE tasks SET plan_id=?,title=?,description=?,due_date=?,priority=?,tag=?,estimated_minutes=?,status=?,completed_at=IF(?="completed",COALESCE(completed_at,NOW()),NULL) WHERE id=? AND deleted_at IS NULL',[...v,v[7],req.params.id]);const [[row]]=await pool.execute('SELECT * FROM tasks WHERE id=? AND deleted_at IS NULL',[req.params.id]);if(!row)return res.status(404).json({error:'Task를 찾을 수 없습니다.'});res.json(row);}));
app.delete('/api/tasks/:id',asyncRoute(async(req,res)=>{const [r]=await pool.execute('UPDATE tasks SET deleted_at=NOW() WHERE id=? AND deleted_at IS NULL',[req.params.id]);res.status(r.affectedRows?204:404).end();}));
app.post('/api/tasks/:id/complete',asyncRoute(async(req,res)=>{const key=String(req.body.completion_key||'').trim();if(!key)return res.status(400).json({error:'completion_key가 필요합니다.'});const c=await pool.getConnection();try{await c.beginTransaction();const [[task]]=await c.execute('SELECT * FROM tasks WHERE id=? AND deleted_at IS NULL FOR UPDATE',[req.params.id]);if(!task){await c.rollback();return res.status(404).json({error:'Task를 찾을 수 없습니다.'});}if(task.status==='completed'){await c.commit();return res.json({task,created_event:false,idempotent:true});}try{await c.execute('INSERT INTO task_completion_events(task_id,completion_key) VALUES(?,?)',[task.id,key]);}catch(e){if(e.code!=='ER_DUP_ENTRY')throw e;}await c.execute("UPDATE tasks SET status='completed',completed_at=NOW() WHERE id=?",[task.id]);await c.commit();const [[row]]=await pool.execute('SELECT * FROM tasks WHERE id=?',[task.id]);res.json({task:row,created_event:true,idempotent:false});}catch(e){await c.rollback();throw e;}finally{c.release();}}));
app.post('/api/tasks/:id/reopen',asyncRoute(async(req,res)=>{await pool.execute("UPDATE tasks SET status='in_progress',completed_at=NULL WHERE id=? AND deleted_at IS NULL",[req.params.id]);const [[row]]=await pool.execute('SELECT * FROM tasks WHERE id=? AND deleted_at IS NULL',[req.params.id]);if(!row)return res.status(404).json({error:'Task를 찾을 수 없습니다.'});res.json(row);}));
app.post('/api/tasks/:id/executions',asyncRoute(async(req,res)=>{const b=req.body,v=[req.params.id,b.start_time,b.end_time,Number(b.actual_minutes),b.blocker_reason||null,b.work_done||null];required(v,['task_id','start_time','end_time','actual_minutes']);const [r]=await pool.execute('INSERT INTO execution_logs(task_id,start_time,end_time,actual_minutes,blocker_reason,work_done) VALUES(?,?,?,?,?,?)',v);const [[row]]=await pool.execute('SELECT * FROM execution_logs WHERE id=?',[r.insertId]);res.status(201).json(row);}));
app.get('/api/tasks/:id/executions',asyncRoute(async(req,res)=>{const [r]=await pool.execute('SELECT * FROM execution_logs WHERE task_id=? ORDER BY start_time DESC,id DESC',[req.params.id]);res.json(r);}));
app.get('/api/executions',asyncRoute(async(req,res)=>{const [r]=await pool.execute('SELECT e.*,t.title task_title,t.plan_id FROM execution_logs e JOIN tasks t ON t.id=e.task_id WHERE t.deleted_at IS NULL ORDER BY e.start_time DESC,e.id DESC');res.json(r);}));

app.get('/api/plans/:id/review',asyncRoute(async(req,res)=>{const [[r]]=await pool.execute(`SELECT COUNT(*) total_tasks,SUM(status='completed') completed_tasks,SUM(status<>'completed' AND due_date<CURRENT_DATE()) overdue_tasks,COALESCE(SUM(estimated_minutes),0) estimated_minutes FROM tasks WHERE plan_id=? AND deleted_at IS NULL`,[req.params.id]);const [[x]]=await pool.execute(`SELECT COUNT(DISTINCT CASE WHEN e.blocker_reason IS NOT NULL AND TRIM(e.blocker_reason)<>'' THEN t.id END) blocked_tasks,COALESCE(SUM(e.actual_minutes),0) actual_minutes FROM tasks t LEFT JOIN execution_logs e ON e.task_id=t.id WHERE t.plan_id=? AND t.deleted_at IS NULL`,[req.params.id]);const out={...r,...x};out.total_tasks=Number(out.total_tasks);out.completed_tasks=Number(out.completed_tasks||0);out.overdue_tasks=Number(out.overdue_tasks||0);out.blocked_tasks=Number(out.blocked_tasks||0);out.estimated_minutes=Number(out.estimated_minutes);out.actual_minutes=Number(out.actual_minutes);out.difference_minutes=out.actual_minutes-out.estimated_minutes;res.json(out);}));
app.get('/api/plans/:id/review/evidence',asyncRoute(async(req,res)=>{const type=req.query.type;const map={total:[`SELECT id,title,status,due_date,estimated_minutes FROM tasks WHERE plan_id=? AND deleted_at IS NULL ORDER BY id`,[req.params.id]],completed:[`SELECT id,title,status,completed_at FROM tasks WHERE plan_id=? AND deleted_at IS NULL AND status='completed' ORDER BY id`,[req.params.id]],overdue:[`SELECT id,title,status,due_date FROM tasks WHERE plan_id=? AND deleted_at IS NULL AND status<>'completed' AND due_date<CURRENT_DATE() ORDER BY id`,[req.params.id]],blocked:[`SELECT DISTINCT t.id,t.title FROM tasks t JOIN execution_logs e ON e.task_id=t.id WHERE t.plan_id=? AND t.deleted_at IS NULL AND e.blocker_reason IS NOT NULL AND TRIM(e.blocker_reason)<>'' ORDER BY t.id`,[req.params.id]],estimated:[`SELECT id,title,estimated_minutes FROM tasks WHERE plan_id=? AND deleted_at IS NULL ORDER BY id`,[req.params.id]],actual:[`SELECT e.id,e.task_id,t.title task_title,e.actual_minutes,e.work_done FROM execution_logs e JOIN tasks t ON t.id=e.task_id WHERE t.plan_id=? AND t.deleted_at IS NULL ORDER BY e.id`,[req.params.id]]};if(!map[type])return res.status(400).json({error:'올바르지 않은 evidence type입니다.'});const [rows]=await pool.execute(...map[type]);res.json({type,rows});}));
app.post('/api/plans/:id/reflection',asyncRoute(async(req,res)=>{const improvement=String(req.body.improvement||'').trim();if(!improvement)return res.status(400).json({error:'개선점을 입력하세요.'});const [r]=await pool.execute('INSERT INTO reflections(plan_id,improvement) VALUES(?,?)',[req.params.id,improvement]);res.status(201).json({id:r.insertId,plan_id:Number(req.params.id),improvement});}));
app.post('/api/reflections/:id/carry',asyncRoute(async(req,res)=>{const c=await pool.getConnection();try{await c.beginTransaction();const [[ref]]=await c.execute('SELECT * FROM reflections WHERE id=? FOR UPDATE',[req.params.id]);if(!ref){await c.rollback();return res.status(404).json({error:'개선점을 찾을 수 없습니다.'});}const b=req.body;const [r]=await c.execute('INSERT INTO plans(title,description,start_date,end_date,priority,success_criteria,estimated_minutes,carried_improvement) VALUES(?,?,?,?,?,?,?,?)',[b.title,b.description||'',b.start_date,b.end_date,allowed(b.priority,['low','medium','high'],'medium'),b.success_criteria,Number(b.estimated_minutes)||0,ref.improvement]);await c.execute('UPDATE reflections SET carried_to_plan_id=? WHERE id=?',[r.insertId,ref.id]);await c.commit();const [[row]]=await pool.execute('SELECT * FROM plans WHERE id=?',[r.insertId]);res.status(201).json(row);}catch(e){await c.rollback();throw e;}finally{c.release();}}));
app.get('/api/reflections',asyncRoute(async(req,res)=>{const [r]=await pool.execute('SELECT * FROM reflections ORDER BY id DESC');res.json(r);}));
app.get('/api/export',asyncRoute(async(req,res)=>{const names=['plans','plan_history','tasks','execution_logs','task_completion_events','reflections'];const out={};for(const n of names){const [r]=await pool.query(`SELECT * FROM ${n} ORDER BY 1`);out[n==='task_completion_events'?'completion_events':n]=r;}out.exported_at=new Date().toISOString();res.setHeader('Content-Disposition','attachment; filename="pds-export.json"');res.json(out);}));
app.get('*',(req,res)=>res.sendFile(path.join(PUBLIC,'index.html')));
app.use((err,req,res,next)=>{console.error(err.code||err.message);res.status(err.status||500).json({error:err.status?err.message:'서버 요청을 처리하지 못했습니다.',code:err.code});});
if(require.main===module){const port=Number(process.env.PORT||3000),host=process.env.HOST||'127.0.0.1';app.listen(port,host,()=>console.log(`PDS Diary: http://${host}:${port}`));}
module.exports=app;
